version: "3"
services:
  order:
    build:
      context: ./build/order
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - database
  product:
    build:
      context: ./build/product
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8081:8080
    depends_on:
      - database
  setting:
    build:
      context: ./build/setting
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8082:8080
    depends_on:
      - database
  database:
    build: 
      context: ./build/database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  mysql_data: